version: '3'
services:
  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '15432:80'
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres-compose-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: 'user@admin.com'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'local'
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
    networks:
      - postgres-compose-network
  site:
    container_name: site
    build:
      context: ./site
      dockerfile: DockerFile
    image: site:tag
    ports:
      - '80:80'
networks:
  postgres-compose-network:
    driver: bridge
