FROM node:lts-alpine as build-stage

# faz da pasta 'app' o diretório atual de trabalho
WORKDIR /app

# copia arquivos e pastas para o diretório atual de trabalho (pasta 'app')
COPY . .

# estágio de produção
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]